---
title: "Privacy Statement"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Privacy Statement}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

tidystats software does not collect or transmit user information, and does not
rely on external services except for hosting the necessary files.

The tidystats Microsoft Word add-in requires an internet connection, but this is only used
to retrieve the files needed to perform its functions of parsing and inserting
statistics into your Word document. All processing is done directly on your
machine.

tidystats software does not contain any user analytics. In other words, I do not
track anything you do when using tidystats. If you like using tidystats, simply
let me know by creating a
[GitHub issue](https://github.com/WillemSleegers/tidystats/issues) or sending an
[e-mail](mailto:tidystats@gmail.com).

Note that Posit does [track](https://cran-logs.rstudio.com) how many times R
packages are downloaded from CRAN, and Microsoft does similar tracking for
Office add-ins.

If you send a support e-mail, your e-mail address will only be used for
tidystats support purposes.
